project_id = "npjlmpadxosdkxwxxnmi"

[functions.send-welcome-email]
verify_jwt = false

[functions.woovi-webhook]
verify_jwt = false

[functions.provision-user-on-a]
verify_jwt = false  

[functions.create-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false